In [1]:
# Good morning! Here's your coding interview problem for today.

# This question was asked by Zillow.

# You are given a 2-d matrix where each cell represents number of coins in that cell. Assuming we start at matrix[0][0], and can only move right or down, find the maximum number of coins you can collect by the bottom right corner.

# For example, in this matrix

# 0 3 1 1
# 2 0 0 4
# 1 5 3 1

# The most we can collect is 0 + 2 + 1 + 5 + 3 + 1 = 12 coins.

In [2]:
import pandas as pd 
import numpy as np

In [3]:
# Create a Random Matrix of [A,B] of Values Between C and D

width = 4
height = 3
rand_low = 0
rand_high = 9

array = np.random.randint(rand_high, size=(height, width))
print(array)

[[7 1 0 6]
 [3 5 4 6]
 [0 7 2 2]]


In [4]:
#path through using the largest adjacent value

# _sum = 0 

# for i in range(6)

In [5]:
# Skip that, create a list of all possible paths, convert to matrix coordinates, and sum. Fund largest sum.

In [6]:
# from top left to right bottom
row = 5
col = 5
 
# to find the path from
# top left to bottom right
def isPath(arr) :
 
    # directions
    Dir = [ [0, 1], [1, 0]]
     
    # queue
    q = []
     
    # insert the top right corner.
    q.append((0, 0))
     
    # until queue is empty
    while(len(q) > 0) :
        p = q[0]
        q.pop(0)
         
        # mark as visited
        arr[p[0]][p[1]] = -1
         
        # destination is reached.
        if(p == (row - 1, col - 1)) :
            return True
             
        # check all four directions
        for i in range(4) :
         
            # using the direction array
            a = p[0] + Dir[i][0]
            b = p[1] + Dir[i][1]
             
            # not blocked and valid
            if(a >= 0 and b >= 0 and a < row and b < col and arr[a][b] != -1) :           
                q.append((a, b))
    return False
   
# Given array
arr = [ [ 0, 0, 0, -1, 0 ],
        [ -1, 0, 0, -1, -1 ],
        [ 0, 0, 0, -1, 0 ],
        [ -1, 0, -1, 0, -1 ],
        [ 0, 0, -1, 0, 0 ] ]
 
# path from arr[0][0] to arr[row][col]
if (isPath(arr)) :
    print("Yes")
else :
    print("No")
 

IndexError: list index out of range

In [ ]:
def numberOfPaths(m, n):
    
    if (m == 1 or n == 1):
        return 1
    
    return  numberOfPaths(m-1, n) + 